#!/bin/sh
set -e

node config-generator.js \
    MEMPOOL.NETWORK=${MEMPOOL_NETWORK} \
    MEMPOOL.HTTP_PORT=${MEMPOOL_HTTP_PORT} \
    MEMPOOL.CACHE_ENABLED=${MEMPOOL_CACHE_ENABLED} \
    CORE_RPC.HOST=${CORE_RPC_HOST} \
    CORE_RPC.PORT=${CORE_RPC_PORT} \
    CORE_RPC.COOKIE=${CORE_RPC_COOKIE} \
    CORE_RPC.COOKIE_PATH=${CORE_RPC_COOKIE_PATH} \
    CORE_RPC.DEBUG_LOG_PATH= \
    ELECTRUM.HOST=${ELECTRUM_HOST} \
    ELECTRUM.PORT=${ELECTRUM_PORT} \
    ELECTRUM.TLS_ENABLED=${ELECTRUM_TLS_ENABLED} \
    DATABASE.HOST=${DATABASE_HOST} \
    DATABASE.DATABASE=${DATABASE_DATABASE} \
    DATABASE.PASSWORD=${DATABASE_PASSWORD} \
    DATABASE.USERNAME=${DATABASE_USERNAME} \
    DATABASE.SOCKET= \
    STATISTICS.ENABLED=${STATISTICS_ENABLED} \
    REDIS.ENABLED=${REDIS_ENABLED} \
    REDIS.UNIX_SOCKET_PATH=${REDIS_UNIX_SOCKET_PATH}

exec "$@"
