FROM 1maa/alpine:edge

RUN apk add --no-cache \
    git \
    inotify-tools \
    nodejs-current \
    nodejs-current-npm \
 && npm install -g \
    bower \
    grunt-cli \
    gulp-cli \
    less \
    less-plugin-clean-css
