name: Docker Setup
description: Sets up a Docker builder

inputs:
  cache-tag:
    description: Registry tag to cache from
    required: true
  context:
    description: Docker build context
    required: true
  docker-hub-user:
    description: User for authentication against Docker Hub
    required: true
  docker-hub-pass:
    description: Docker Hub password of the given user
    required: true
  tags:
    description: List of docker image names
    required: true

runs:
  using: "composite"
  steps:
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
        username: ${{ inputs.docker-hub-user }}
        password: ${{ inputs.docker-hub-pass }}
    - uses: docker/build-push-action@v4
      with:
        cache-from: type=registry,ref=${{ inputs.cache-tag }}
        cache-to: type=inline
        context: ${{ inputs.context }}
        push: true
        tags: ${{ inputs.tags }}
