name: PHP Docker image builder
description: Sets up a Docker builder tailored for PHP images

inputs:
  tag:
    description: Tag of the base PHP image
    required: true
  dev-tag:
    description: Tag of the development PHP image
    required: true
  docker-hub-user:
    description: User for authentication against Docker Hub
    required: true
  docker-hub-pass:
    description: Docker Hub password of the given user
    required: true
  dockerfile:
    description: Path to the Dockerfile
    required: true

runs:
  using: "composite"
  steps:
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
        username: ${{ inputs.docker-hub-user }}
        password: ${{ inputs.docker-hub-pass }}
    - uses: docker/build-push-action@v4
      with:
        cache-from: type=registry,ref=${{ inputs.tag }}
        cache-to: type=inline
        context: php
        file: ${{ inputs.dockerfile }}
        push: true
        tags: ${{ inputs.tag }}
        target: php
    - uses: docker/build-push-action@v4
      with:
        cache-from: type=registry,ref=${{ inputs.tag }}
        cache-to: type=inline
        context: php
        file: ${{ inputs.dockerfile }}
        push: true
        tags: ${{ inputs.dev-tag }}
        target: php-dev
