name: Generic Docker image builder
description: Sets up a Docker builder

inputs:
  build-arg:
    description: First Build argument
    required: true
  cache-tag:
    description: Registry tag to cache from
    required: true
  context:
    description: Docker build context
    required: true
  docker-hub-user:
    description: User for authentication against Docker Hub
    required: true
  docker-hub-pass:
    description: Docker Hub password of the given user
    required: true
  dockerfile:
    description: Path to the Dockerfile
    required: true
  platforms:
    description: Build platforms
    required: true
  tags:
    description: List of docker image names
    required: true

runs:
  using: "composite"
  steps:
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker-hub-user }}
        password: ${{ inputs.docker-hub-pass }}
    - uses: docker/build-push-action@v6
      with:
        build-args: |
          ${{ inputs.build-arg }}
        cache-from: type=registry,ref=${{ inputs.cache-tag }}
        cache-to: type=inline
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        platforms: ${{ inputs.platforms }}
        push: true
        tags: ${{ inputs.tags }}
