FROM alpine:3.6

ENV PHP_VERSION=7.2.0RC3

ENV CFLAGS="-O3 -march=x86-64"

RUN apk add --no-cache \
    # generic dependencies for compiling the source
    alpine-sdk \
    autoconf \
    automake \
    file \
    flex \
    libtool \
    re2c \

    # dependencies for building specific extensions
    curl-dev \
    gd-dev \
    libpng-dev \
    libressl-dev \
    libsodium-dev \
    libxml2-dev \
    postgresql-dev \
    readline-dev \
    zlib-dev \
 && cd /tmp \
 && curl -OsS https://downloads.php.net/~remi/php-${PHP_VERSION}.tar.gz \
 && tar zxof php-${PHP_VERSION}.tar.gz \
 && cd ./php-${PHP_VERSION} \
 && ./configure \
    EXTENSION_DIR="/usr/lib/php" \

    --prefix=/usr \
    --sysconfdir=/etc/php/cli \
    --with-config-file-path=/etc/php/cli \
    --with-config-file-scan-dir=/etc/php/cli/conf.d \

    --enable-cli \
    --disable-fpm \
    --disable-cgi \
    --disable-phpdbg \

    --enable-exif \
    --enable-mbstring \
    --enable-opcache \
    --enable-pcntl \
    --enable-soap \
    --enable-sockets \
    --enable-zip \

    --with-curl \
    --with-gd \
    --with-openssl \
    --with-pdo-mysql \
    --with-pdo-pgsql \
    --with-readline \
    --with-sodium \
    --with-zlib \
 && make -j$(grep "cpu cores" /proc/cpuinfo | wc -l) \
 && make install \
 && pecl install \
    apcu \
    ds \
    igbinary \
    redis \
#    xdebug \
 && chmod +x /usr/lib/php/*.so \
 && cd /tmp \
 && rm -rf php-${PHP_VERSION} \
 && tar zxof php-${PHP_VERSION}.tar.gz \
 && cd ./php-${PHP_VERSION} \
 && ./configure \
    EXTENSION_DIR="/usr/lib/php" \

    --prefix=/usr \
    --sysconfdir=/etc/php/fpm \
    --with-config-file-path=/etc/php/fpm \
    --with-config-file-scan-dir=/etc/php/fpm/conf.d \

    --enable-fpm \
    --disable-cli \
    --disable-cgi \
    --disable-phpdbg \

    --enable-exif \
    --enable-mbstring \
    --enable-opcache \
    --enable-soap \
    --enable-sockets \
    --enable-zip \

    --with-curl \
    --with-gd \
    --with-openssl \
    --with-pdo-mysql \
    --with-pdo-pgsql \
    --with-sodium \
    --with-zlib \
 && make -j$(grep "cpu cores" /proc/cpuinfo | wc -l) \
 && mv sapi/fpm/php-fpm /usr/sbin/php-fpm


FROM 1maa/alpine:3.6

COPY etc /etc/php

COPY --from=0 /usr/bin/php      /usr/bin/php
COPY --from=0 /usr/sbin/php-fpm /usr/sbin/php-fpm
COPY --from=0 /usr/lib/php/*.so /usr/lib/php/

RUN apk add --no-cache \
    libcurl \
    libgd \
    libpq \
    libsodium \
    libxml2 \
    readline \
 && rm /etc/php/mods-available/libsodium.ini

EXPOSE 9000

CMD ["/usr/sbin/php-fpm", "-R"]
