FROM 1maa/python:2.7

RUN apk add --no-cache \
    openssh \
 && echo 'root:root' | chpasswd \
 && sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

COPY ssh/* /etc/ssh/

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
