FROM 1maa/python:2.7

RUN apk add --no-cache \
    openssh \
 && echo 'root:root' | chpasswd \
 && sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

COPY ssh/* /etc/ssh/

RUN chmod 644 /etc/ssh/* \
 && chmod 600 /etc/ssh/ssh_host_dsa_key \
 && chmod 600 /etc/ssh/ssh_host_ecdsa_key \
 && chmod 600 /etc/ssh/ssh_host_ed25519_key \
 && chmod 600 /etc/ssh/ssh_host_rsa_key

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
