#!/bin/sh
set -e

# Runtime overrides - read env vars defined in docker compose

__MAINNET_ENABLED__=${MAINNET_ENABLED}
__TESTNET_ENABLED__=${TESTNET_ENABLED}
__TESTNET4_ENABLED__=${TESTNET_ENABLED}
__SIGNET_ENABLED__=${SIGNET_ENABLED}
__LIQUID_ENABLED__=${LIQUID_ENABLED}
__LIQUID_TESTNET_ENABLED__=${LIQUID_TESTNET_ENABLED}
__ITEMS_PER_PAGE__=${ITEMS_PER_PAGE}
__KEEP_BLOCKS_AMOUNT__=${KEEP_BLOCKS_AMOUNT}
__NGINX_PROTOCOL__=${NGINX_PROTOCOL}
__NGINX_HOSTNAME__=${NGINX_HOSTNAME}
__NGINX_PORT__=${NGINX_PORT}
__BLOCK_WEIGHT_UNITS__=${BLOCK_WEIGHT_UNITS}
__MEMPOOL_BLOCKS_AMOUNT__=${MEMPOOL_BLOCKS_AMOUNT}
__BASE_MODULE__=${BASE_MODULE}
__ROOT_NETWORK__=${ROOT_NETWORK:=}
__MEMPOOL_WEBSITE_URL__=${MEMPOOL_WEBSITE_URL}
__LIQUID_WEBSITE_URL__=${LIQUID_WEBSITE_URL}
__MINING_DASHBOARD__=${MINING_DASHBOARD}
__LIGHTNING__=${LIGHTNING}
__AUDIT__=${AUDIT}
__MAINNET_BLOCK_AUDIT_START_HEIGHT__=${MAINNET_BLOCK_AUDIT_START_HEIGHT}
__TESTNET_BLOCK_AUDIT_START_HEIGHT__=${TESTNET_BLOCK_AUDIT_START_HEIGHT}
__SIGNET_BLOCK_AUDIT_START_HEIGHT__=${SIGNET_BLOCK_AUDIT_START_HEIGHT}
__ACCELERATOR__=${ACCELERATOR}
__ACCELERATOR_BUTTON__=${ACCELERATOR_BUTTON}
__SERVICES_API__=${SERVICES_API}
__PUBLIC_ACCELERATIONS__=${PUBLIC_ACCELERATIONS}
__HISTORICAL_PRICE__=${HISTORICAL_PRICE}
__ADDITIONAL_CURRENCIES__=${ADDITIONAL_CURRENCIES}
__STRATUM_ENABLED__=${STRATUM_ENABLED}

# Export as environment variables to be used by envsubst
export __MAINNET_ENABLED__
export __TESTNET_ENABLED__
export __TESTNET4_ENABLED__
export __SIGNET_ENABLED__
export __LIQUID_ENABLED__
export __LIQUID_TESTNET_ENABLED__
export __ITEMS_PER_PAGE__
export __KEEP_BLOCKS_AMOUNT__
export __NGINX_PROTOCOL__
export __NGINX_HOSTNAME__
export __NGINX_PORT__
export __BLOCK_WEIGHT_UNITS__
export __MEMPOOL_BLOCKS_AMOUNT__
export __BASE_MODULE__
export __ROOT_NETWORK__
export __MEMPOOL_WEBSITE_URL__
export __LIQUID_WEBSITE_URL__
export __MINING_DASHBOARD__
export __LIGHTNING__
export __AUDIT__
export __MAINNET_BLOCK_AUDIT_START_HEIGHT__
export __TESTNET_BLOCK_AUDIT_START_HEIGHT__
export __SIGNET_BLOCK_AUDIT_START_HEIGHT__
export __ACCELERATOR__
export __ACCELERATOR_BUTTON__
export __SERVICES_API__
export __PUBLIC_ACCELERATIONS__
export __HISTORICAL_PRICE__
export __ADDITIONAL_CURRENCIES__
export __STRATUM_ENABLED__

envsubst < /srv/browser/resources/config.template.js > /srv/browser/resources/config.js

exec "$@"
