FROM 1maa/alpine:3.4

RUN apk add --no-cache postgresql=9.5.3-r1

ENV PGDATA /var/lib/postgresql/9.5

USER postgres

CMD echo -e "This image is not runnable by itself, it must be extended.\nSee 1maa/postgres-dev for an example."
