FROM 1maa/alpine:3.5

RUN apk add --no-cache \
    postgresql \
    postgresql-contrib

ENV PGDATA /var/lib/postgresql/9.6

USER postgres

CMD echo -e "This image is not runnable by itself, it must be extended.\nSee 1maa/postgres-dev for an example."
