FROM 1maa/php-cli:5.6

RUN apk add --no-cache \
    alpine-sdk \
    autoconf \
    php5-dev \
    php5-pear \
 && sed -i 's@exec $PHP -C -n -q@exec $PHP -C -q@' /usr/bin/pecl # fixes nasty PECL bug documented by user bluebinary at: http://serverfault.com/a/612038
