FROM 1maa/php:5.6-dev

RUN apk add --no-cache \
    php5-fpm \
 && sed -i 's@listen = 127.0.0.1:9000@listen = [::]:9000@' /etc/php5/php-fpm.conf \
 && sed -i 's@user = nobody@user = root@' /etc/php5/php-fpm.conf \
 && sed -i 's@group = nobody@group = root@' /etc/php5/php-fpm.conf

COPY dev/supervisord.conf.fpm-56 /etc/supervisor/conf.d/supervisord.conf

EXPOSE 9000

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
