FROM 1maa/php:7.0

RUN apk add --no-cache \
    git \
    openssh \
    php7-xdebug \
 && ssh-keygen -A \
 && echo 'root:root' | chpasswd \
 && sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

COPY dev/profile.70 /etc/profile
COPY dev/conf.d/*   /etc/php7/conf.d/
COPY dev/tooling/*  /usr/local/bin/

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
