FROM 1maa/php-cli:7.1-xdebug

RUN apk add --no-cache \
    apache2 \
    php7-apache2@edge-community \
 && mkdir /run/apache2

EXPOSE 80 443

STOPSIGNAL SIGWINCH

CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]
