FROM 1maa/php:7.0-xdebug

RUN apk add --no-cache \
    php7-fpm \
    supervisor \
 && sed -i 's@listen = 127.0.0.1:9000@listen = 9000@' /etc/php7/php-fpm.d/www.conf \
 && sed -i 's@user = nobody@user = root@' /etc/php7/php-fpm.d/www.conf \
 && sed -i 's@group = nobody@group = root@' /etc/php7/php-fpm.d/www.conf

COPY dev/supervisord.conf.fpm-70 /etc/supervisor/conf.d/supervisord.conf

EXPOSE 9000

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
