name: Reusable multiarch build

on:
  workflow_call:
    inputs:
      target:
        type: string
        required: true
      version:
        type: string
        required: false
        default: '0.0.0'
      tag:
        type: string
        required: false
        default: 'latest'
    secrets:
      gh_token:
        required: true
      hub_token:
        required: true

jobs:
  build:
    name: Build ${{ inputs.target }} ${{ inputs.version }} on ${{ matrix.runners }}
    runs-on: ${{ matrix.runners }}
    strategy:
      fail-fast: false
      matrix:
        runners:
          - "ubuntu-24.04"
          - "ubuntu-24.04-arm"
    env:
      VERSION: ${{ inputs.version }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
      - uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.gh_token }}
      - uses: docker/bake-action@6614cfa25eff9a0b2b2697efb0b6159e7680d584 # v7.2.0
        with:
          provenance: false
          push: true
          sbom: false
          targets: ${{ inputs.target }}

  merge:
    name: Merge ${{ inputs.target }} ${{ inputs.tag }} image
    runs-on: ubuntu-24.04
    needs:
      - build
    steps:
      - uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
      - uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: 1maa
          password: ${{ secrets.hub_token }}
      - run: |
          docker buildx imagetools create \
            -t 1maa/${{ inputs.target }}:${{ inputs.tag }} \
            ghcr.io/1ma/${{ inputs.target }}:${{ inputs.tag }}-X64 \
            ghcr.io/1ma/${{ inputs.target }}:${{ inputs.tag }}-ARM64

  cleanup:
    name: Cleanup stale ${{ inputs.target }} images
    runs-on: ubuntu-24.04
    needs:
      - merge
    steps:
      - uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.gh_token }}
      - uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5.0.0
        with:
          package-name: ${{ inputs.target }}
          package-type: container
          delete-only-untagged-versions: true
          min-versions-to-keep: 0
